//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate.SiteAdmin
{


    public partial class AgentWork
    {

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.DropDownList ddlAgentFilter;

        protected global::System.Web.UI.WebControls.GridView gvAgentWork;
    }
}
