//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate.SiteAdmin
{


    public partial class Dashboard
    {

        protected global::System.Web.UI.WebControls.Literal litTotalAgents;

        protected global::System.Web.UI.WebControls.Literal litActiveAgents;

        protected global::System.Web.UI.WebControls.Literal litTotalProperties;

        protected global::System.Web.UI.WebControls.Literal litTotalInquiries;

        /// <summary>
        /// litTotalSell control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalSell;

        protected global::System.Web.UI.WebControls.GridView gvRecentAgents;
    }
}
