//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate
{


    public partial class Properties
    {

        /// <summary>
        /// lnkAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkAll;

        /// <summary>
        /// lnkVilla control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkVilla;

        /// <summary>
        /// lnkPenthouse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkPenthouse;

        /// <summary>
        /// lnkTownhouse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkTownhouse;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// lblEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmpty;

        /// <summary>
        /// dlProperties control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DataList dlProperties;
    }
}
